### PR TITLE
Enable OpenCL in Debian package

### PR DESCRIPTION
**Pull request by larsmans**
I'm not sure if a PR on GitHub is the right way to get this to you, but here's a patch to build the OpenCL backend in the Debian packages. I've successfully used it to produce packages for Linux Mint.

This PR is based off your branch `debian/sid` on alioth. Only the last two commits are mine.

### CODE REVIEW

**Comment by ghisvail** [comment]
Hey Lars, thanks for showing interest in the OpenCL backend of ArrayFire. First thing to do is to file a bug in the Debian bug tracker against the source package `arrayfire`. Use severity `wishlist` and ask for a request for the OpenCL backend. That way, if someone else was also interested, then this bug will be the central point to track progress.

You will be pleased to know that I have already done some work on it and that a release in Debian unstable is to be expected soon. I cannot accept your patch however, since the content of the `debian` folder has changed quite significantly since the initial debianization done in this branch. You can have a look at the repository hosted on Debian science if you're curious.

On a side note, a slight variation from your proposal is that `libarrayfire-dev` will be a common package shared by `libarrayfire-cpu-dev` and `libarrayfire-opencl-dev`.

**Comment by larsmans** [comment]
> You can have a look at the repository hosted on Debian science if you're curious.

Do you mean [this repo](https://anonscm.debian.org/cgit/debian-science/packages/arrayfire.git)? That's actually where I got the code. This PR isn't really meant to apply to your GitHub repo, it just seemed like the easiest way to get the patches to you.

> On a side note, a slight variation from your proposal is that libarrayfire-dev will be a common package shared by libarrayfire-cpu-dev and libarrayfire-opencl-dev.

I'm sorry, I don't understand how this is different from the way I set things up. I've put all the headers into the common `-dev` package and the `.so` into individual `cpu-dev` and `opencl-dev`.

**Comment by ghisvail** [comment]
> I'm sorry, I don't understand how this is different from the way I set things up.

I meant:

```
Package: libarrayfire-dev
...
Depends:
 ${misc:Depends}
...

Package: libarrayfire-cpu-dev
...
Depends:
 libarrayfire-dev,
 ${misc:Depends}
...

Package: libarrayfire-opencl-dev
...
Depends:
 libarrayfire-dev,
 ${misc:Depends}
...
```

Plus, I will add an additional package `libarrayfire-all-dev`, which installs all ArrayFire backends:

```
Package: libarrayfire-all-dev
...
Depends:
 libarrayfire-cpu-dev,
 libarrayfire-opencl-dev,
 ${misc:Depends}
...
```

**Comment by larsmans** [comment]
I actually considered that setup, but I chose against it because the `libarrayfire-dev` package seemed useless without either of the backend `-dev` packages. No client program would link, right? So I made `libarrayfire-dev` depend on `libarrayfire-cpu-dev | libarrayfire-opencl-dev`.

**Comment by ghisvail** [comment]
Feel free to correct if I am wrong here. According to your current d/control, if I `apt-get install libarrayfire-opencl-dev`, then neither the public includes nor the necessary `ArrayFireConfig*.cmake` dispatcher get installed. So the development environment would be incomplete.

Previously, doing `apt-get install libarrayfire-cpu-dev` provided a complete development environment, and I'd want the `OpenCL`, `CUDA` and future `unified` backends to remain that way.

For that to happen, the only solution I can think of is to factor the public headers and `ArrayFireConfig*.cmake` out to a "useless" package (`libarrayfire-dev` or `libarrayfire-common-dev`, naming convention still left to be discussed) on which all `libarrayfire-$(backend)-dev` would depend on.

Thoughts?

**Comment by larsmans** [comment]
Hm, you're right there. I guess your setup is cleaner.

**Comment by larsmans** [comment]
The only problem with your setup is that `apt-get install libarrayfire-dev` installs a useless package; but I guess that naming them `-all-dev` and `-common-dev` should be clear enough.

**Comment by ghisvail** [comment]
Actually, `libarrayfire-dev` is not technically "useless". Assuming you come up with an API-compatible alternative implementation of `ArrayFire`, then all you need is the public headers and the `ArrayFireConfig*.cmake`, which is what this package provides.

I admit this is an extremely improbable use case though.

**Pull request closed without merging**
